name: CI

on:
  push:
    branches: [main]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: fish-actions/install-fish@v1.1.0

      - name: Install abbreviation-tips with Fisher
        uses: fish-shop/install-plugin@v1
        with:
          plugin-manager: fisher
          plugins: gazorby/fifc

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        # Homebrew is only missing from ubuntu images per https://github.com/actions/runner-images/issues/6283
        if: matrix.os == 'ubuntu-latest'

      - name: Install fzf and fd
        run: brew install fzf fd

      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@v1
        with:
          pattern: tests/**.fish
        # timeout in case tests get stuck on fzf
        timeout-minutes: 3

  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: fish-actions/install-fish@v1

      - uses: fish-actions/syntax-check@v1

  # check Fish format
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: fish-actions/install-fish@v1

      - uses: fish-actions/format-check@v1

  # check Markdown and Yaml format
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionsx/prettier@v2
        with:
          args: --check .
